# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SpectaclesSwift' do
  use_frameworks!

  # Pods for SpectaclesSwift
	pod "Spectacles"

  target 'SpectaclesSwiftTests' do
    inherit! :search_paths
	pod "Spectacles"

  end

end
